### 1. Basics of Matrix in Python
- You can represent a matrix using a list of lists:



In [2]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(f"Original matrix: {matrix}")

Original matrix: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


### 2. Accessing Elements


In [5]:
print(matrix[0][1])  # Output: 2 (first row, second column)


2


### 3. Matrix Traversal


#### a. Row-wise


In [6]:
# Accessing elements in a 2D list, meaning print whoe matrix as a single line

matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

for row in range(len(matrix)):
    for item in range(len(matrix)):
        print(matrix[row][item], end=" ")




1 2 3 4 5 6 7 8 9 

#### b. Index-based

In [ ]:
for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        print(matrix[i][j], end=" ")

1 2 3 4 5 6 7 8 9 

### 4. Common Operations
`🧠 Tips:`
- len(matrix) gives number of rows.
- len(matrix[0]) gives number of columns (assuming all rows are equal length)
- Always access elements with matrix[i][j] — i is row, j is column

#### a. Transpose

In [ ]:
# item = [[0]*3 for _ in range(3)]

# print(item)

 

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [70]:

matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]  

for i in range(len(matrix)):  # rows
    for j in range(len(matrix[0])):  # cols
        print(f"matrix[{i}][{j}] = {matrix[i][j]}")


matrix[0][0] = 1
matrix[0][1] = 2
matrix[0][2] = 3
matrix[1][0] = 4
matrix[1][1] = 5
matrix[1][2] = 6
matrix[2][0] = 7
matrix[2][1] = 8
matrix[2][2] = 9


In [ ]:
# matrix[1][1]==> matrix[1][1]
# matrix[1][2]==> matrix[2][1]
# matrix[1][3]==> matrix[3][1]


    
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]  



rows, cols = len(matrix), len(matrix[0])
transposed = [[0] * rows for _ in range(cols)]

for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        transposed[i][j] = matrix[j][i]



# print(transposed)     
for row in transposed:
    # print(item)
    for item in row:
        print(f"{item:5}", end=' ')
    print()
     
 


    1     4     7 
    2     5     8 
    3     6     9 


In [7]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]  
rows, cols = len(matrix), len(matrix[0])
transposed = [[0] * rows for _ in range(cols)]

for i in range(len(matrix)):
     for j in range(len(matrix[0])):
          transposed[i][j] = matrix[j][i]
          print(transposed[i][j], end=' ')
    
     print()


1 4 7 
2 5 8 
3 6 9 


## Repeat!

In [26]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]

rows = len(matrix)
cols = len(matrix[0])  

transposed = [[0]*rows for _ in range(cols)]


for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        transposed[i][j] = matrix[j][i]
        print(transposed[i][j], end=' ')
    print()
      



1 4 7 
2 5 8 
3 6 9 


### For Non-Square matrix

In [34]:
matrix = [
    [1, 2],
    [4, 5],
    [7, 8]]

rows = len(matrix)
cols = len(matrix[0])  

# print(f'Row#: {rows}--- Columns#: {cols}')

transposed = [[0]*rows for _ in range(cols)]
# print(transposed)

for i in range(len(transposed)):
    for j in range(len(transposed[0])):
        transposed[i][j] = matrix[j][i]
        print(transposed[i][j], end='  ')
    print()

1  4  7  
2  5  8  


In [ ]:
matrix = [
    [1, 2, 3],
    [4, 5, 6]]

rows = len(matrix)
cols = len(matrix[0])  

# print(f'Row#: {rows}--- Columns#: {cols}')

transposed = [[0]*rows for _ in range(cols)]
# print(transposed)

for i in range(len(transposed)):
    for j in range(len(transposed[0])):
        transposed[i][j] = matrix[j][i]
        print(transposed[i][j], end='  ')
    print()

1  4  
2  5  
3  6  


#### 🔁 b. Rotate Matrix 90° Clockwise

## 📌 Algorithm:
- Transpose the matrix.
- Reverse each row



In [122]:
matrix = [
    [1, 2, 3],
    [4, 5, 6]]

# row = [10, 20, 30]
## rever-1)
# for i in reversed(row):
#     print(i)
## rever-2(alternative)
# for j in range(len(row)):
#     print(row[len(row)-j-1])

# print(f'Row#: {rows}--- Columns#: {cols}')
rows = len(matrix)
cols = len(matrix[0])
transposed = [[0]*rows for _ in range(cols)]


# print(transposed)

for i in range(len(transposed)):
    for j in range(len(transposed[0])):
        transposed[i][j] = matrix[j][i]
    #     print(transposed[i][j], end='  ')     
    # print()

for k in range(len(transposed)):
    # print(transposed[len(transposed) - k - 1])
    transposed[k].reverse()
    print(transposed[k])

[4, 1]
[5, 2]
[6, 3]


In [125]:
def transpose(matrix):
    rows, cols = len(matrix), len(matrix[0])
    
    # Step 1: Create a new matrix of size cols x rows initialized to 0s
    transposed = [[0] * rows for _ in range(cols)]
    
    # Step 2: Assign transposed[j][i] = matrix[i][j]
    for i in range(rows):
        for j in range(cols):
            transposed[j][i] = matrix[i][j]
    
    return transposed


def rotate_90_clockwise(matrix):
    # Step 1: Transpose the matrix
    transposed = transpose(matrix)

    # Step 2: Reverse each row of the transposed matrix
    for row in transposed:
        row.reverse()

    return transposed

matrix = [
    [1, 2, 3],
    [4, 5, 6]]

rotated = rotate_90_clockwise(matrix)

for k in range(len(rotated)):
    # print(transposed[len(transposed) - k - 1])
    print(rotated[k])
# print(rotated)


[4, 1]
[5, 2]
[6, 3]


### Matrix-Row Reversal 

In [126]:
matrix = [
    [1, 2, 3],
    [4, 5, 6]]


for i in range(len(matrix)):
    # print(matrix[i])
    for j in range(len(matrix[0])):
        matrix[i].reverse()
        print(matrix[i][j], end=' ')
    print()

3 2 1 
6 5 4 


In [ ]:
matrix = [
    [1, 2, 3],
    [4, 5, 6]]

print(f'Reversed Version {matrix[::-1]}')


Reversed Version [[4, 5, 6], [1, 2, 3]]


In [136]:
def reverse_columns(matrix):
    return matrix[::-1]

matrix = [
    [1, 2, 3],
    [4, 5, 6]]

print(f'Reversed Version {reverse_columns(matrix)}')

Reversed Version [[4, 5, 6], [1, 2, 3]]


### 5. Using NumPy (Highly Recommended for Performance)

In [156]:
import numpy as np

matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

arr = np.array(matrix) # This conever the list to Numpy array

print(arr.T) # Take transpose of array 
print()
print(np.rot90(arr)) # Rotate matrix by 90 Degree
print()
print(np.flip(arr, axis=0))  # Flip vertically
print()
print(np.flip(arr, axis=1))  # Flip horizontally


[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[3 6 9]
 [2 5 8]
 [1 4 7]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]

[[3 2 1]
 [6 5 4]
 [9 8 7]]


### 6. Advanced Interview Concepts
#### a. Spiral Matrix Traversal


In [ ]:
def spiral_order(matrix):
    res = []
    while matrix:
        res += matrix.pop(0)
        if matrix and matrix[0]:
            for row in matrix:
                res.append(row.pop())
        if matrix:
            res += matrix.pop()[::-1]
        if matrix and matrix[0]:
            for row in matrix[::-1]:
                res.append(row.pop(0))
    return res


matx = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]


print(spiral_order(matx))

[1, 2, 3, 6, 9, 8, 7, 4, 5] 

## Revision after a large break
- I am resuming my python logic building after a long break, after being stuck in tight routine!

In [ ]:
# Matrix representations
print("Matrix representations")
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(matrix)

# accessing a particular element
print()
print("accessing a particular element")
print(matrix[1][2])

In [ ]:
def traverse_matrix(matrix):
    rows = len(matrix)
    cols = len(matrix[0])

    print("🔸 Row-wise Traversal:")
    for i in range(rows):
        for j in range(cols):
            print(matrix[i][j], end='  ')
        print()

    print("🔹 Column-wise Traversal:")
    for j in range(cols):
        for i in range(rows):
            print(matrix[i][j], end='  ')
        print()

In [ ]:
traverse_matrix(matrix)

In [ ]:
# Row-wise traveral.....

# matrix = [
#     [1, 2, 3],
#     [4, 5, 6],
#     [7, 8, 9]
# ]
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8]
]

# valid_matrix = all(len(row) == len(matrix[0]) for row in matrix)
valid_matrix = all(len(row) == len(matrix[0]) for row in matrix)

print(valid_matrix)

if valid_matrix == True:
    for i in range(len(matrix)):
        print(i) # printing row only
        for j in range(len(matrix[0])):
            print(matrix[i][j], end= '  ')
        print()
else:
    print('Matrix is invalid :)')

    

# l_row = len(m_matrix)
# l_col = len(m_matrix[0])

# print(l_row, l_col)




False
Matrix is invalid :)


In [108]:
# Column-wise traveral.....


matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
 

# valid_matrix = all(len(row) == len(matrix[0]) for row in matrix)
valid_matrix = all(len(row) == len(matrix[0]) for row in matrix)

print(valid_matrix)

if valid_matrix == True:
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            print(matrix[j][i], end= '  ')
        print()
else:
    print('Matrix is invalid :)')


True
1  4  7  
2  5  8  
3  6  9  


In [111]:
l_row = len(matrix)
l_col = len(matrix[0])

print(l_row, l_col)


all(len(row) == len(matrix[0]) for row in matrix) # Compare each row length with the 1st row length to ensure that all rows are equal


3 3


True

In [ ]:
# 🔹 2. Creating a Transpose of a Matrix only work for square-matrix :)

matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]


for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            matrix[j][i] = matrix[j][i]
            print(matrix[j][i], end= '  ')
        print()



1  4  7  
2  5  8  
3  6  9  


In [179]:
# 🔹 2. Creating a Transpose of a Matrix only work for all

# matrix = [
#     [1, 2, 3],
#     [4, 5, 6],
#     [7, 8, 9]
# ]

# Invalid Case
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8]
]


valid_matrix = all(len(row) == len(matrix[0]) for row in matrix)

if valid_matrix:
    rows = len(matrix)
    cols = len(matrix[0])
    
    # Step 1: Create empty transposed matrix
    transposed = [[0] * rows for _ in range(cols)]

    # Step 2: Fill by swapping indices
    for i in range(rows):
        for j in range(cols):
            transposed[j][i] = matrix[i][j]

    # ✅ Correctly print the transposed matrix
    for row in transposed:
        print(row)

else:
    print("Invalid Matrix :(")


Invalid Matrix :(


# 🔁 Spiral Matrix Traversal
### Optimal with boundaries ✅